export const SEARCH_DATA = "SEARCH_DATA";
export const PAGINATION = "PAGINATION";
export const FETCH_ITEMS_PENDING = "FETCH_ITEMS_PENDING";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_ERROR = "FETCH_ITEMS_ERROR";

export const FETCH_BEST_PRICE_PENDING = "FETCH_BEST_PRICE_PENDING";
export const FETCH_BEST_PRICE_SUCCESS = "FETCH_BEST_PRICE_SUCCESS";
export const FETCH_BEST_PRICE_ERROR = "FETCH_BEST_PRICE_ERROR";